locale: "it"

backend:
  name: git-gateway
  branch: main

# local_backend: true

media_folder: static/images
public_folder: /images

collections:
  - label: Page
    name: page
    delete: false
    editor:
      preview: true
    files:
      - file: content/pages/home.md
        label: Home Page
        name: home-page
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: "" }
          - { label: Immagine Principale, name: featuredImage, widget: image }
          - { label: Titolo, name: title, widget: string }
          - {
              label: Sottotitolo,
              name: subtitle,
              widget: string,
              required: false,
            }

          - {
              label: Messaggio focus,
              name: focusmessage,
              widget: object,
              fields:
                [
                  {
                    label: Data Messaggio Focus,
                    name: messagedate,
                    widget: "datetime",
                    default: "",
                    date_format: "DD.MM.YYYY",
                    format: "L",
                    required: false,
                  },
                  {
                    label: Titolo Messaggio Focus,
                    name: messagetitle,
                    widget: string,
                    required: false,
                  },
                  {
                    label: Descrizione Messaggio Focus,
                    name: messagedescription,
                    widget: string,
                    required: false,
                  },
                ],
            }

          - {
              label: Sezioni Focus,
              name: blurbs,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Title, name: title, widget: string },
                  { label: Body, name: body, widget: markdown },
                ],
            }
          - {
              label: Listino Prezzi,
              name: prices,
              widget: list,
              fields:
                [
                  { label: Titolo, name: category, widget: string },
                  {
                    label: Prezzi,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Prodotto, name: label, widget: string },
                        { label: Prezzo, name: price, widget: number },
                      ],
                  },
                ],
            }

          # Contacts Section
          - {
              label: Contatti,
              name: contacts,
              widget: object,
              fields:
                [
                  { label: Titolo, name: contacttitle, widget: string },
                  {
                    label: Descrizione,
                    name: contactdescription,
                    widget: string,
                  },
                  {
                    label: Indirizzo,
                    name: contactaddress,
                    widget: object,
                    fields:
                      [
                        { label: Via, name: contactstreet, widget: string },
                        { label: Citt√†, name: contactcity, widget: string },
                      ],
                  },
                  { label: Telefono, name: contactphone, widget: string },
                  { label: Email, name: contactemail, widget: string },
                ],
            }
          # Footer Section
          - {
              label: Footer,
              name: footer,
              widget: object,
              fields:
                [
                  {
                    label: Social Links. Enter 'null' for empty Links,
                    name: social,
                    widget: object,
                    fields:
                      [
                        {
                          label: Enter Facebook URL,
                          name: facebook,
                          widget: string,
                          required: false,
                        },
                        {
                          label: Enter Instagram URL,
                          name: instagram,
                          widget: string,
                          required: false,
                        },
                        {
                          label: Enter Twitter URL,
                          name: twitter,
                          widget: string,
                          required: false,
                        },
                      ],
                  },
                ],
            }
